name: brechfete
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animations: ^2.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_splash_screen: ^1.0.4
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_easyloading: ^3.0.5
  flutter_staggered_animations: ^1.0.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  injectable: ^1.5.3
  injectable_generator: ^1.5.4
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  lottie: ^1.4.1
  material_design_icons_flutter: ^5.0.6996
  qr_flutter: ^4.0.0
  scrollable_positioned_list: ^0.3.2
  shared_preferences: ^2.0.15
  simple_gradient_text: ^1.2.3
  sticky_headers: ^0.3.0+2
  tabbed_sliverlist: ^0.1.0
  table_calendar: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  #flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1

#flutter_icons:
#  android: true
#  ios: true
#  image_path: assets/images/samvit_color_logo.png

# flutter_native_splash-production.yaml
#flutter_native_splash:
#  color: "#ffffff"
#  image: assets/images/samvit_logo.png
#  color_dark: "#121212"
#  image_dark: assets/images/samvit_logo.png
#
#  android_12:
#    image: assets/images/samvit_logo.png
#    icon_background_color: "#ffffff"
#    image_dark: assets/images/samvit_logo.png
#    icon_background_color_dark: "#121212"
#
#  web: false
#  ios: true
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie_files/done.json
    - assets/lottie_files/confirm.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
